flyway.url = jdbc:snowflake://MHGPCWH-OKB18206.snowflakecomputing.com/?db=TEST_DB&warehouse=COMPUTE_WH

flyway.locations=filesystem:scripts

flyway.placeholders.database=TEST_DB

flyway.placeholders.schema1=schema1

flyway.placeholders.schema2=schema2